apiVersion: v1
kind: Namespace
metadata:
  name: python-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api-deployment
  namespace: python-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      namespace: python-api
      labels:
        app: python-api
    spec:
      containers:
        - name: python-api
          image: cr.yandex/crp73or0r2lq6e167atp/python-api:__VERSION__
          imagePullPolicy: Always
