---
- name: Converge
  hosts: all
  vars:
    script_v3: false
  pre_tasks:
    - name: Detect python3 version
      ansible.builtin.command: "python3 --version"
      register: cmd_res
      changed_when: false
      failed_when: false
    - name: Set python version of script to 3
      ansible.builtin.set_fact:
        script_v3: true
      when: cmd_res.rc == 0
    - name: Download SystemD replacer v3
      become: true
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl3.py
        dest: /systemctl.py
        mode: "a+x"
      when: script_v3
    - name: Download SystemD replacer v2
      become: true
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl.py
        dest: /systemctl.py
        mode: "a+x"
      when: not script_v3
    - name: Create systemd directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        recurse: true
      loop:
        - /run/systemd/system
        - /usr/lib/systemd/system
    - name: Replace systemctl
      become: true
      ansible.builtin.copy:
        src: /systemctl.py
        remote_src: true
        dest: /usr/bin/systemctl
        mode: "+x"
        force: true
    - name: ReCollect system info
      ansible.builtin.setup:
    # - name: Get Clickhouse IP from docker engine
    #   ansible.builtin.command: "docker inspect -f {{  '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' }} clickhouse-01"
    #   register: cmd_res
    #   changed_when: false
    #   failed_when: cmd_res.rc != 0
    #   delegate_to: localhost
    # - name: Set Clickhouse IP to facts
    #   ansible.builtin.set_fact:
    #     clickhouse_ipv4: "{{ cmd_res.stdout }}"
    #   when: cmd_res.rc == 0
  tasks:
    - name: "Include vector-role"
      ansible.builtin.include_role:
        name: "vector-role"
      vars:
        clickhouse_user: logger
        clickhouse_password: logger
        clickhouse_table: some_log
        clickhouse_db: logs
        vector_config_path: "/etc/vector"
        clickhouse_ipv4: 51.250.12.68
