---
- name: Install Nginx and Git
  become: true
  ansible.builtin.yum:
    name: nginx, git
    state: present
- name: Check Lighthouse config exists
  register: lh_exists
  ansible.builtin.file:
    path: "{{ lighthouse_path }}/app.js"
  ignore_errors: true
- name: Install Lighthouse from Github
  become: true
  when: lh_exists.state == "absent"
  ansible.builtin.git:
    repo: https://github.com/VKCOM/lighthouse.git
    version: master
    dest: "{{ lighthouse_path }}"
