---
- name: Install Vector by DNF
  become: true
  when: ansible_pkg_mgr=="dnf"
  ansible.builtin.dnf:
    name: 'https://yum.vector.dev/stable/vector-0/{{ vector_arch }}/vector-{{ vector_version }}-1.{{ vector_arch }}.rpm'
    disablerepo:
    - "*"
    disable_gpg_check: true
